### PR TITLE
Only set GSI provisioned throughput for provisioned billing modes. Fixes #1017

### LINKED ISSUE #1017: v5.2.0 breaking change? AttributeError: type object 'Meta' has no attribute 'read_capacity_units'
The release of 5.2.0 broke GlobalSecondaryIndex syntax that worked on 5.1.0. Requesting to add a note about it in release notes for 5.2.0

## Broken syntax in 5.2.0, but working in 5.1.0
```
class UserRangeKey(GlobalSecondaryIndex):
    class Meta:
        index_name = "user-range-key-index"
        projection = AllProjection()

    user_range_key = UnicodeAttribute(hash_key=True)
```

## Valid syntax in 5.2.0

```
class UserRangeKey(GlobalSecondaryIndex):
    class Meta:
        index_name = "user-range-key-index"
        projection = AllProjection()
        billing_mode = "PAY_PER_REQUEST"

    user_range_key = UnicodeAttribute(hash_key=True)
```

Lines it breaks in is in PR [#996](https://github.com/pynamodb/PynamoDB/pull/996/commits/9fbcae919f76cbb3884f5468ec3ebcdf61148749#diff-192353ecf550dccd373608dd09309f29240c4a39a658cb67c2b5ddafbbd9ff1cR197)

### PR DESCRIPTION
**Pull request by jpinner-lyft**

### CODE REVIEW

File: pynamodb/indexes.py [hunk 1]
```diff
@@ -141,7 +141,7 @@ def _hash_key_attribute(cls):
                 return attr_cls
 
     @classmethod
-    def _get_schema(cls) -> Dict:
+    def _get_schema(cls, add_provisioned_throughput: bool) -> Dict:
```
Comment (ikonst) [inline pynamodb/indexes.py:144]: nit - like to make such params that are primitive type and have no implied/natural order (e.g. not `pow(base, exp)`) to be kwargs-only
```suggestion
    def _get_schema(cls, *, add_provisioned_throughput: bool) -> Dict:
```

**Review by ikonst — APPROVED** [review]

**Review by ikonst — APPROVED** [review]
Notably no test caught this
