### PR TITLE
Workaround for _convert_to_request_dict change

### PR DESCRIPTION
**Pull request by ikonst**
botocore 1.28 [changed](https://github.com/boto/botocore/pull/2785) the signature of private method `botocore.client.BaseClient._convert_to_request_dict` adding an `endpoint_url` parameter. We are updating pynamodb to inspect the signature and add this parameter as needed.

P.S. we would probably need to backport this to 5.x.

### CODE REVIEW

**Comment by garrettheel** [comment]
Worth noting that https://github.com/pynamodb/PynamoDB/pull/1079 will also fix this particular issue (by relying on less private APIs, but not all)

**Review by garrettheel — APPROVED** [review]
lgtm, and +1 to backporting to a 5.x release (I'd rather not ship 6.0 yet)

**Comment by DeepSpace2** [comment]
@ikonst @garrettheel

Thanks for the quick fix.

I'd love to get this as a 5.2.2 hotfix rather than waiting to 6.0.0.

**Comment by dmulter** [comment]
Would love to see this backported to 4.x as a 4.3.4 release.

**Comment by kashishshah881** [comment]
Can we get this back-ported to 4.x too?

**Comment by ikonst** [comment]
@dmulter see https://github.com/pynamodb/PynamoDB/pull/1130

**Comment by ikonst** [comment]
Should be available at https://pypi.org/project/pynamodb/4.4.0/

**Comment by MirzaBaig715** [comment]
I am getting this error` _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'` on` dynamodb==5.0.3` and `botocore==1.20.112`.

**Comment by dobeerman** [comment]
> @ikonst I am getting this error` _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'` with `dynamodb==5.0.3` `botocore==1.20.112`.

I had the same issue with one lambda containerized. I used aws public image for the lambda with the tag `public.ecr.aws/lambda/python:3.8`. Recently AWS rolled out the update which also includes update for botocore to v1.29.xxx.
I simply changed the image to `public.ecr.aws/lambda/python:3.8.2023.02.20.11` and now it works.

Also, if you do install requirements in this container, make sure you use target in the command `RUN pip3 install -r requirements.txt --target ${LAMBDA_TASK_ROOT}` which will also override the preinstalled botocore (if its included into the requirements)

**Comment by ikonst** [comment]
Are you suggesting that recent pynamodb doesn't work well with old botocore 1.20?

**Comment by MirzaBaig715** [comment]
@dobeerman I am using lambda containerization with this image `lambci/lambda:build-python3.8`.

**Comment by MirzaBaig715** [comment]
> > @ikonst I am getting this error` _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'` with `dynamodb==5.0.3` `botocore==1.20.112`.
> 
> I had the same issue with one lambda containerized. I used aws public image for the lambda with the tag `public.ecr.aws/lambda/python:3.8`. Recently AWS rolled out the update which also includes update for botocore to v1.29.xxx. I simply changed the image to `public.ecr.aws/lambda/python:3.8.2023.02.20.11` and now it works.
> 
> Also, if you do install requirements in this container, make sure you use target in the command `RUN pip3 install -r requirements.txt --target ${LAMBDA_TASK_ROOT}` which will also override the preinstalled botocore (if its included into the requirements)

@dobeerman I am using lambda containerization with this image `lambci/lambda:build-python3.8`.

**Comment by bersek36** [comment]
> > @ikonst I am getting this error` _convert_to_request_dict() missing 1 required positional argument: 'endpoint_url'` with `dynamodb==5.0.3` `botocore==1.20.112`.
> 
> I had the same issue with one lambda containerized. I used aws public image for the lambda with the tag `public.ecr.aws/lambda/python:3.8`. Recently AWS rolled out the update which also includes update for botocore to v1.29.xxx. I simply changed the image to `public.ecr.aws/lambda/python:3.8.2023.02.20.11` and now it works.
> 
> Also, if you do install requirements in this container, make sure you use target in the command `RUN pip3 install -r requirements.txt --target ${LAMBDA_TASK_ROOT}` which will also override the preinstalled botocore (if its included into the requirements)

Thanks a lot. This fixed my bug.
