### PR TITLE
Fix exception message

### LINKED ISSUE #1017: v5.2.0 breaking change? AttributeError: type object 'Meta' has no attribute 'read_capacity_units'
The release of 5.2.0 broke GlobalSecondaryIndex syntax that worked on 5.1.0. Requesting to add a note about it in release notes for 5.2.0

## Broken syntax in 5.2.0, but working in 5.1.0
```
class UserRangeKey(GlobalSecondaryIndex):
    class Meta:
        index_name = "user-range-key-index"
        projection = AllProjection()

    user_range_key = UnicodeAttribute(hash_key=True)
```

## Valid syntax in 5.2.0

```
class UserRangeKey(GlobalSecondaryIndex):
    class Meta:
        index_name = "user-range-key-index"
        projection = AllProjection()
        billing_mode = "PAY_PER_REQUEST"

    user_range_key = UnicodeAttribute(hash_key=True)
```

Lines it breaks in is in PR [#996](https://github.com/pynamodb/PynamoDB/pull/996/commits/9fbcae919f76cbb3884f5468ec3ebcdf61148749#diff-192353ecf550dccd373608dd09309f29240c4a39a658cb67c2b5ddafbbd9ff1cR197)

### LINKED ISSUE #1155: Exception message is always `None`
@ikonst, I made a PR some time ago which fixes this: #1113. Is there a timeline of when we can expect it to be released?

### PR DESCRIPTION
**Pull request by ikonst**
Backport of #1113 to 5.x branch.

Fixes #1155.

### CODE REVIEW

**Comment by ikonst** [comment]
FYI @pauliokas

**Review by anandswaminathan — APPROVED** [review]
